### ISSUE TITLE
Privacy Manifest file

### ISSUE THREAD

**Issue by claypark12** [google/app-check#49]
Apple recently released a [Describing use of required reason API](https://developer.apple.com/documentation/bundleresources/privacy_manifest_files/describing_use_of_required_reason_api) , which should include a privacy manifest by spring 2024. Since this SDK is using UserDefaults, I think this SDK will need the Privacy Manifest file, so I create an issue.

**Comment by tichise** [comment]
List of places where UserDefaults is used

app-check/AppCheckCore/Sources/AppAttestProvider/Storage/GACAppAttestKeyIDStorage.m:23 | UserDefaults | /// The `NSUserDefaults` suite name for the storage location of the app attest key ID.
-- | -- | --
app-check/AppCheckCore/Sources/AppAttestProvider/Storage/GACAppAttestKeyIDStorage.m:23 | NSUserDefaults | /// The `NSUserDefaults` suite name for the storage location of the app attest key ID.
app-check/AppCheckCore/Sources/AppAttestProvider/Storage/GACAppAttestKeyIDStorage.m:27 | UserDefaults | /// The app attest key ID is stored using `NSUserDefaults` .
app-check/AppCheckCore/Sources/AppAttestProvider/Storage/GACAppAttestKeyIDStorage.m:27 | NSUserDefaults | /// The app attest key ID is stored using `NSUserDefaults` .
app-check/AppCheckCore/Sources/AppAttestProvider/Storage/GACAppAttestKeyIDStorage.m:28 | UserDefaults | @property(nonatomic, readonly) NSUserDefaults *userDefaults;
app-check/AppCheckCore/Sources/AppAttestProvider/Storage/GACAppAttestKeyIDStorage.m:28 | NSUserDefaults | @property(nonatomic, readonly) NSUserDefaults *userDefaults;
app-check/AppCheckCore/Sources/AppAttestProvider/Storage/GACAppAttestKeyIDStorage.m:35 | UserDefaults | _userDefaults = [[NSUserDefaults alloc] initWithSuiteName:kKeyIDStorageDefaultsSuiteName];
app-check/AppCheckCore/Sources/AppAttestProvider/Storage/GACAppAttestKeyIDStorage.m:35 | NSUserDefaults | _userDefaults = [[NSUserDefaults alloc] initWithSuiteName:kKeyIDStorageDefaultsSuiteName];
